Repository Jondolf/avian, pull requests merged in 2023-09, with the labels that each got.

#140 Fix `Transform` initialization for children and refactor `prepare.rs`
  src/plugins/prepare.rs
Labels: enhancement, bugfix

#144 Clarify that forces are in world space and improve force docs
  src/components/forces.rs
Labels: documentation

#145 Fix math cross-platform determinism
  crates/bevy_xpbd_2d/Cargo.toml
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/snapshots/bevy_xpbd_3d__tests__cubes_simulation_is_deterministic_across_machines.snap
  src/math/double.rs
  src/math/mod.rs
  src/math/single.rs
  src/tests.rs
Labels: enhancement

#151 Combine `insert` calls into bundles to reduce archetype count
  src/plugins/prepare.rs
Labels: enhancement

#152 Avoid incremental updates to Qbvh
  src/plugins/spatial_query/mod.rs
  src/plugins/spatial_query/pipeline.rs
  src/plugins/spatial_query/system_param.rs
Labels: performance, bugfix, spatial queries

#156 Fix contact stability for non-convex colliders
  crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs
  crates/bevy_xpbd_3d/snapshots/bevy_xpbd_3d__tests__cubes_simulation_is_deterministic_across_machines.snap
  src/constraints/penetration.rs
  src/plugins/narrow_phase.rs
  src/plugins/solver.rs
Labels: bugfix, collision detection, solver

#155 Collision post processing
  crates/bevy_xpbd_2d/examples/one_way_platform_2d.rs
  src/lib.rs
  src/plugins/narrow_phase.rs
  src/plugins/setup.rs
Labels: enhancement, examples, collision detection

#160 Add `Trigger` alias for `Sensor` and improve `Sensor` docs
  src/components/collider.rs
Labels: documentation, collision detection
