Repository Jondolf/avian, pull requests merged in 2023-11, with the labels that each got.

#215 Update to `actions/checkout@v4`.
  .github/workflows/ci.yml
Labels: ci

#216 docs: Use more backticks.
  crates/bevy_xpbd_3d/examples/trimesh_shapes_3d.rs
  src/lib.rs
  src/plugins/collision/mod.rs
  src/plugins/spatial_query/pipeline.rs
Labels: documentation

#220 Use intradoc links rather than #method anchors.
  src/components/collider.rs
  src/components/forces.rs
  src/components/layers.rs
  src/components/locked_axes.rs
  src/components/mass_properties.rs
  src/components/mod.rs
  src/plugins/collision/mod.rs
  src/plugins/spatial_query/mod.rs
  src/plugins/spatial_query/ray_caster.rs
  src/plugins/spatial_query/system_param.rs
Labels: documentation

#219 Move x comparison in broad phase up to early-out as soon as possible
  src/plugins/collision/broad_phase.rs
Labels: enhancement, performance, collision detection

#214 Unify physics time APIs with `Time<Physics>` and `Time<Substeps>`
  crates/benches_common_3d/src/lib.rs
  crates/bevy_xpbd_3d/examples/basic_dynamic_character.rs
  crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs
  crates/bevy_xpbd_3d/snapshots/bevy_xpbd_3d__tests__cubes_simulation_is_deterministic_across_machines.snap
  crates/examples_common_2d/src/lib.rs
  crates/examples_common_3d/src/lib.rs
  src/constraints/mod.rs
  src/lib.rs
  src/plugins/collision/broad_phase.rs
  src/plugins/integrator.rs
  src/plugins/mod.rs
  src/plugins/setup/mod.rs
  src/plugins/setup/time.rs
  src/plugins/sleeping.rs
  src/plugins/solver.rs
  src/resources.rs
Labels: enhancement, scheduling

#222 Improve character controller examples
  crates/bevy_xpbd_2d/Cargo.toml
  crates/bevy_xpbd_2d/examples/dynamic_character_2d/main.rs
  crates/bevy_xpbd_2d/examples/dynamic_character_2d/plugin.rs
  crates/bevy_xpbd_2d/examples/kinematic_character_2d/main.rs
  crates/bevy_xpbd_2d/examples/kinematic_character_2d/plugin.rs
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/assets/character_controller_demo.glb
  crates/bevy_xpbd_3d/examples/dynamic_character_3d/main.rs
  crates/bevy_xpbd_3d/examples/dynamic_character_3d/plugin.rs
  crates/bevy_xpbd_3d/examples/kinematic_character_3d/main.rs
  crates/bevy_xpbd_3d/examples/kinematic_character_3d/plugin.rs
  src/plugins/collision/mod.rs
Labels: examples

#225 Fix fixed timestep using `max_delta_overstep`
  src/plugins/setup/mod.rs
  src/plugins/setup/time.rs
Labels: bugfix, scheduling

#226 Expand AABBs by prediction distance
  crates/bevy_xpbd_3d/snapshots/bevy_xpbd_3d__tests__cubes_simulation_is_deterministic_across_machines.snap
  src/plugins/collision/broad_phase.rs
  src/plugins/collision/contact_reporting.rs
  src/plugins/collision/narrow_phase.rs
Labels: bugfix, collision detection

#227 Include entity Name in logged warning for overlapping colliders
  src/plugins/solver.rs
Labels: enhancement, debug tools

#228 Reduce verbosity of schedule log messages to trace
  src/plugins/setup/mod.rs
Labels: enhancement, debug tools

#230 Fix system order ambiguities, and add a test for it
  src/plugins/prepare.rs
  src/plugins/spatial_query/mod.rs
  src/tests.rs
Labels: enhancement, tests, determinism

#234 docs: Fix incorrect docs for mass component auto-initialization
  src/components/mod.rs
Labels: documentation

#236 Don't overwrite schedules when adding plugin
  src/plugins/setup/mod.rs
Labels: enhancement, scheduling

#238 Take child collider rotation into account for contact normals
  src/plugins/solver.rs
Labels: bugfix, collision detection, solver

#242 Fix mesh visibility not being reset when physics debug is disabled
  src/plugins/debug/mod.rs
Labels: bugfix, debug tools

#241 Filter collisions between children of the same rigidbody in broad phase
  src/plugins/collision/broad_phase.rs
Labels: enhancement, performance, collision detection

#247 Add Serde serialization with `serialize` feature
  .github/workflows/ci.yml
  crates/bevy_xpbd_2d/Cargo.toml
  crates/bevy_xpbd_3d/Cargo.toml
  src/components/collider.rs
  src/components/forces.rs
  src/components/layers.rs
  src/components/locked_axes.rs
  src/components/mass_properties.rs
  src/components/mod.rs
  src/components/rotation.rs
  src/constraints/joints/distance.rs
  src/constraints/joints/fixed.rs
  src/constraints/joints/mod.rs
  src/constraints/joints/prismatic.rs
  src/constraints/joints/revolute.rs
  src/constraints/joints/spherical.rs
  src/constraints/penetration.rs
  src/plugins/collision/broad_phase.rs
  src/plugins/collision/contact_query.rs
  src/plugins/collision/contact_reporting.rs
  src/plugins/collision/mod.rs
  src/plugins/collision/narrow_phase.rs
  src/plugins/debug/configuration.rs
  src/plugins/setup/time.rs
  src/plugins/solver.rs
  src/plugins/spatial_query/pipeline.rs
  src/plugins/spatial_query/query_filter.rs
  src/plugins/spatial_query/ray_caster.rs
  src/plugins/spatial_query/shape_caster.rs
  src/plugins/sync.rs
  src/resources.rs
Labels: enhancement

#251 Added variant TriMeshWithFlags to ComputedCollider, fix #248
  src/components/collider.rs
  src/plugins/prepare.rs
Labels: enhancement, collision detection

#253 Allow collider scaling with `position_to_transform` disabled
  src/plugins/sync.rs
Labels: bugfix, scheduling

#250 Fix rotations when center of mass is offset
  src/components/world_queries.rs
  src/plugins/solver.rs
  src/plugins/sync.rs
  src/utils.rs
Labels: solver

#255 Use any_orthogonal_vector to get orthogonal vector
  src/constraints/joints/prismatic.rs
Labels: bugfix, solver

#267 Fix tests and doc examples, make `cargo test` compile
  src/components/collider.rs
  src/constraints/mod.rs
  src/plugins/collision/contact_query.rs
  src/tests.rs
Labels: tests

#268 Scale debug rendering of center of mass dot by axis lengths
  src/plugins/debug/mod.rs
Labels: debug tools
