Repository Jondolf/avian, pull requests merged in 2023-07, with the labels that each got.

#55 Add `collider-from-mesh` feature and make `bevy_render` optional
  .github/workflows/ci.yml
  crates/bevy_xpbd_2d/Cargo.toml
  crates/bevy_xpbd_3d/Cargo.toml
  src/components/collider.rs
  src/lib.rs
Labels: enhancement

#56 Add `LinearDamping` and `AngularDamping`
  src/components/mod.rs
  src/lib.rs
  src/plugins/integrator.rs
  src/plugins/setup.rs
Labels: enhancement

#58 Support applying force at point and automatically clearing external force and torque
  src/components/mod.rs
  src/lib.rs
  src/plugins/integrator.rs
Labels: enhancement

#59 Use entity index for QBVH nodes instead of entity bits
  src/plugins/spatial_query/mod.rs
  src/plugins/spatial_query/pipeline.rs
  src/plugins/spatial_query/ray_caster.rs
  src/plugins/spatial_query/shape_caster.rs
  src/plugins/spatial_query/system_param.rs
Labels: bug

#61 Use masks instead of collision layers for `SpatialQueryFilter`
  src/plugins/spatial_query/query_filter.rs
Labels: enhancement

#62 Rename `CollisionLayers` methods `with_group`, `without_group` etc. to `add_group`, `remove_group`
  src/components/layers.rs
Labels: enhancement

#63 Support multiple hits for shape casts
  src/plugins/spatial_query/mod.rs
  src/plugins/spatial_query/ray_caster.rs
  src/plugins/spatial_query/shape_caster.rs
  src/plugins/spatial_query/system_param.rs
Labels: enhancement

#64 Add `LockedAxes`
  src/components/locked_axes.rs
  src/components/mod.rs
  src/components/rotation.rs
  src/components/world_queries.rs
  src/constraints/angular_constraint.rs
  src/constraints/position_constraint.rs
  src/lib.rs
  src/plugins/integrator.rs
  src/plugins/setup.rs
  src/plugins/solver.rs
  src/plugins/spatial_query/system_param.rs
Labels: enhancement

#60 Add PhysicsTimestep mode to run only once with a fixed delta
  src/plugins/setup.rs
  src/resources.rs
Labels: enhancement

#65 Implement Debug for Collider
  src/components/collider.rs
Labels: enhancement

#66 Update to Bevy 0.11
  README.md
  crates/bevy_xpbd_2d/Cargo.toml
  crates/bevy_xpbd_2d/examples/chain_2d.rs
  crates/bevy_xpbd_2d/examples/collision_layers.rs
  crates/bevy_xpbd_2d/examples/fixed_joint_2d.rs
  crates/bevy_xpbd_2d/examples/move_marbles.rs
  crates/bevy_xpbd_2d/examples/prismatic_joint_2d.rs
  crates/bevy_xpbd_2d/examples/ray_caster.rs
  crates/bevy_xpbd_2d/examples/revolute_joint_2d.rs
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/examples/chain_3d.rs
  crates/bevy_xpbd_3d/examples/cubes.rs
  crates/bevy_xpbd_3d/examples/custom_broad_phase.rs
  crates/bevy_xpbd_3d/examples/custom_constraint.rs
  crates/bevy_xpbd_3d/examples/fixed_joint_3d.rs
  crates/bevy_xpbd_3d/examples/prismatic_joint_3d.rs
  crates/bevy_xpbd_3d/examples/revolute_joint_3d.rs
  crates/examples_common_2d/Cargo.toml
  crates/examples_common_2d/src/lib.rs
  crates/examples_common_3d/Cargo.toml
  crates/examples_common_3d/src/lib.rs
  src/collision.rs
  src/constraints/mod.rs
  src/lib.rs
  src/plugins/debug.rs
  src/plugins/integrator.rs
  src/plugins/mod.rs
  src/plugins/prepare.rs
  src/plugins/setup.rs
  src/plugins/solver.rs
  src/plugins/sync.rs
  src/resources.rs
  src/tests.rs
Labels: enhancement

#70 Fixes for spatial queries
  src/plugins/mod.rs
  src/plugins/spatial_query/mod.rs
  src/plugins/spatial_query/pipeline.rs
  src/plugins/spatial_query/ray_caster.rs
  src/plugins/spatial_query/shape_caster.rs
  src/plugins/spatial_query/system_param.rs
  src/utils.rs
Labels: enhancement, bugfix

#71 Add basic dynamic and kinematic character controller examples
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/examples/basic_dynamic_character.rs
  crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs
Labels: examples

#72 Improved docs
  src/components/locked_axes.rs
  src/components/mass_properties.rs
  src/components/mod.rs
  src/lib.rs
  src/plugins/integrator.rs
  src/plugins/mod.rs
  src/plugins/spatial_query/system_param.rs
Labels: documentation

#76 Add debug rendering axes and joints and improve configuration API
  crates/bevy_xpbd_2d/examples/many_shapes.rs
  src/constraints/joints/fixed.rs
  src/constraints/joints/mod.rs
  src/constraints/joints/prismatic.rs
  src/constraints/joints/revolute.rs
  src/constraints/joints/spherical.rs
  src/lib.rs
  src/plugins/debug/configuration.rs
  src/plugins/debug/mod.rs
Labels: enhancement

#77 Move `SpatialQuery` methods to `SpatialQueryPipeline`
  src/plugins/spatial_query/pipeline.rs
  src/plugins/spatial_query/system_param.rs
Labels: enhancement

#78 Add `enabled` flag to `PhysicsDebugConfig` to globally disable debug rendering at runtime
  src/plugins/debug/configuration.rs
  src/plugins/debug/mod.rs
Labels: enhancement

#79 Add `trimesh_with_flags` and `trimesh_from_bevy_mesh_with_flags`
  src/components/collider.rs
Labels: enhancement, collision detection

#80 Add PhysicsTimescale resource for slow-motion or fast-forward simulation
  src/lib.rs
  src/plugins/setup.rs
  src/resources.rs
Labels: enhancement, scheduling

#81 Use world-space center of mass in penetration constraint
  src/constraints/penetration.rs
Labels: bugfix, solver

#82 Add `clear` methods for ray and shape hits and clear the hits on disable
  src/plugins/spatial_query/mod.rs
  src/plugins/spatial_query/ray_caster.rs
  src/plugins/spatial_query/shape_caster.rs
Labels: enhancement, spatial queries

#83 Expand AABBs only in the movement direction
  src/plugins/broad_phase.rs
Labels: enhancement, performance, collision detection

#84 Improve simulation stability when object are far from world origin
  src/collision.rs
  src/components/mod.rs
  src/components/world_queries.rs
  src/constraints/joints/mod.rs
  src/constraints/joints/prismatic.rs
  src/constraints/penetration.rs
  src/constraints/position_constraint.rs
  src/lib.rs
  src/plugins/integrator.rs
  src/plugins/prepare.rs
  src/plugins/setup.rs
  src/plugins/solver.rs
  src/utils.rs
Labels: enhancement

#86 Add back global contact positions
  src/collision.rs
  src/constraints/penetration.rs
Labels: enhancement, bugfix, collision detection

#91 Add criterion benchmarks
  crates/benches_common_3d/Cargo.toml
  crates/benches_common_3d/src/lib.rs
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/benches/cubes.rs
Labels: performance

#90 Use contact manifolds instead of single contacts for collisions
  crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs
  src/collision.rs
  src/constraints/penetration.rs
  src/plugins/debug/mod.rs
  src/plugins/solver.rs
Labels: enhancement, bugfix, collision detection

#95 Add `ExternalImpulse` and `ExternalAngularImpulse`
  README.md
  src/components/forces.rs
  src/components/mod.rs
  src/lib.rs
  src/plugins/integrator.rs
  src/plugins/prepare.rs
  src/plugins/setup.rs
  src/plugins/sleeping.rs
Labels: enhancement

#98 Filter operation reodered for a little performance boost
  src/collision.rs
Labels: enhancement, performance

#97 Store local contact normals and transform them into world-space at each solve
  src/collision.rs
  src/constraints/penetration.rs
  src/plugins/debug/mod.rs
  src/plugins/solver.rs
Labels: enhancement, solver

#96 Support `Transform` for moving and positioning bodies
  src/lib.rs
  src/plugins/mod.rs
  src/plugins/sync.rs
  src/tests.rs
Labels: enhancement

#103 Fix typo in docs
  src/lib.rs
Labels: documentation

#101 Automatically add `Position` and `Rotation` for colliders
  crates/bevy_xpbd_2d/examples/ray_caster.rs
  src/plugins/broad_phase.rs
  src/plugins/prepare.rs
  src/plugins/sync.rs
Labels: enhancement
