Repository Jondolf/avian, pull requests merged in 2023-08, with the labels that each got.

#105 feature: Add DistanceJoint and 2D and 3D examples.
  crates/bevy_xpbd_2d/examples/distance_joint_2d.rs
  crates/bevy_xpbd_3d/examples/distance_joint_3d.rs
  src/constraints/joints/distance.rs
  src/constraints/joints/mod.rs
  src/constraints/mod.rs
  src/plugins/debug/mod.rs
  src/plugins/solver.rs
Labels: enhancement, examples, solver

#109 Debug render rigid body axes at center of mass
  crates/bevy_xpbd_3d/examples/distance_joint_3d.rs
  src/plugins/debug/configuration.rs
  src/plugins/debug/mod.rs
Labels: enhancement, debug tools

#107 Added text that explained how to use the example 'chain_3d'
  crates/bevy_xpbd_3d/examples/chain_3d.rs
Labels: enhancement, examples

#117 Add "Bounciness" and "Elasticity" aliases for `Restitution`
  src/components/mod.rs
Labels: documentation

#118 Clamp coefficient of restitution between 0 and 1 and improve restitution docs
  src/components/mod.rs
  src/lib.rs
  src/plugins/prepare.rs
Labels: documentation, enhancement

#120 Add `current_position` getter for `RigidBodyQueryItem`
  crates/bevy_xpbd_3d/examples/custom_constraint.rs
  src/components/world_queries.rs
  src/constraints/joints/distance.rs
  src/constraints/joints/mod.rs
  src/constraints/joints/prismatic.rs
  src/constraints/penetration.rs
Labels: enhancement

#123 Clarify that external forces and impulses are local
  src/components/forces.rs
Labels: documentation

#126 Register `CoefficientCombine`
  src/plugins/setup.rs
Labels: enhancement

#128 Correct time dilation for FixedUpdate schedule.
  src/plugins/setup.rs
Labels: bugfix, scheduling

#127 Fix center of mass and inertia computations and add tests
  src/components/mass_properties.rs
  src/components/world_queries.rs
Labels: tests, bugfix

#133 Avoid allocate on spatial queries. ray_hits_callback, shape_hits_callback, intersections_callback
  src/plugins/spatial_query/pipeline.rs
  src/plugins/spatial_query/system_param.rs
Labels: enhancement, spatial queries

#52 Dynamic friction fix
  crates/bevy_xpbd_2d/examples/many_shapes.rs
  src/plugins/solver.rs
  src/utils.rs
Labels: bugfix, solver

#134 Fix 2d `position_to_transform` changing child `Transform` z-component
  src/plugins/sync.rs
Labels: bugfix

#136 Make Rotation & PreviousRotation derive PartialEq
  src/components/rotation.rs
Labels: enhancement

#138 Fix tests on mac m1
  src/components/world_queries.rs
Labels: tests
