Repository Jondolf/avian, pull requests merged in 2023-12, with the labels that each got.

#270 docs: Added Character Controller recommendation for Bevy Tnua what supports Bevy XPBD
  src/lib.rs
Labels: documentation

#278 Apply scale in `Collider::set_shape`
  src/components/collider.rs
Labels: bugfix, collision detection

#283 Ignore static-static collisions in broad phase
  src/plugins/collision/broad_phase.rs
Labels: bugfix, collision detection

#284 Fix rotation change detection in integrator
  src/plugins/integrator.rs
Labels: bugfix

#285 Fix static body handling in `update_aabb_intervals`
  src/plugins/collision/broad_phase.rs
Labels: bugfix, collision detection

#286 Fix `DistanceJoint` distance limits
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/examples/distance_joint_3d.rs
  src/constraints/joints/distance.rs
  src/constraints/joints/mod.rs
Labels: bugfix, solver

#266 Preserve collisions between inactive entities, add sensor example
  crates/bevy_xpbd_2d/examples/sensor.rs
  src/plugins/collision/narrow_phase.rs
Labels: bugfix, collision detection
