Repository Jondolf/avian, pull requests merged in 2024-06, with the labels that each got.

#367 Implement `RegularPolygon` colliders with a custom shape
  src/math/double.rs
  src/math/single.rs
  src/plugins/collision/collider/parry/mod.rs
  src/plugins/collision/collider/parry/primitives2d.rs
  src/plugins/debug/gizmos.rs
Labels: enhancement, collision detection

#373 Improve trimesh docs
  src/plugins/collision/collider/parry/mod.rs
Labels: documentation

#374 Apply collider scale before physics instead of afterwards
  src/plugins/collision/collider_backend.rs
Labels: bugfix

#375 Fix collider scale for child rigid bodies
  src/plugins/collision/collider_backend.rs
Labels: bugfix

#377 Speed up `ColliderTransform` propagation and extract collider hierarchy logic into `ColliderHierarchyPlugin`
  crates/bevy_xpbd_2d/Cargo.toml
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/snapshots/bevy_xpbd_3d__tests__cubes_simulation_is_deterministic_across_machines.snap
  src/plugins/collision/collider/backend.rs
  src/plugins/collision/collider/hierarchy.rs
  src/plugins/collision/collider/mod.rs
  src/plugins/collision/mod.rs
  src/plugins/mod.rs
Labels: performance, breaking change

#380 Refactor and speed up transform propagation and hierarchies further
  src/plugins/collision/collider/backend.rs
  src/plugins/collision/collider/hierarchy.rs
  src/plugins/collision/collider/mod.rs
  src/plugins/mod.rs
  src/plugins/prepare.rs
  src/plugins/sync/ancestor_marker.rs
  src/plugins/sync/mod.rs
  src/tests.rs
Labels: performance, breaking change

#381 Make sensors not contribute to mass properties
  src/components/mass_properties.rs
  src/plugins/collision/collider/backend.rs
  src/plugins/collision/collider/mod.rs
Labels: bugfix, breaking change

#378 Rework deferred collider initialization
  .github/workflows/ci.yml
  crates/bevy_xpbd_2d/Cargo.toml
  crates/bevy_xpbd_3d/Cargo.toml
  crates/bevy_xpbd_3d/examples/collider_constructors.rs
  crates/bevy_xpbd_3d/examples/dynamic_character_3d/main.rs
  crates/bevy_xpbd_3d/examples/kinematic_character_3d/main.rs
  crates/examples_common_3d/Cargo.toml
  src/components/mass_properties.rs
  src/lib.rs
  src/plugins/collision/collider/mod.rs
  src/plugins/collision/collider/parry/mod.rs
  src/plugins/collision/collider_backend.rs
  src/plugins/setup/mod.rs
  src/tests.rs
Labels: breaking change

#388 Fix angular corrections for some 3D joints
  src/constraints/joints/fixed.rs
  src/constraints/joints/prismatic.rs
  src/constraints/joints/revolute.rs
Labels: bugfix, solver

#386 Support default layers and density for `ColliderConstructorHierarchy`
  src/plugins/collision/collider/constructor.rs
  src/plugins/collision/collider/mod.rs
  src/plugins/collision/collider_backend.rs
Labels: enhancement
