Repository Jondolf/avian, pull requests merged in 2024-01, with the labels that each got.

#290 docs: use the read function for iterating over events
  src/plugins/collision/contact_reporting.rs
Labels: documentation

#291 docs: corrects other outdated calls to .iter
  src/plugins/collision/contact_reporting.rs
Labels: documentation

#294 Fix `Time` inconsistency after substepping loop
  src/plugins/setup/mod.rs
Labels: bugfix, scheduling

#300 Adding Collider::round_cuboid
  src/components/collider.rs
Labels: enhancement, collision detection

#305 Add section about camera following jitter to FAQ
  src/lib.rs
  src/plugins/setup/time.rs
Labels: documentation

#307 Add intersection and point queries to `Collider`
  src/components/collider.rs
Labels: enhancement, collision detection

#308 Debug render contact normals
  src/plugins/debug/configuration.rs
  src/plugins/debug/mod.rs
  src/plugins/debug/renderer.rs
Labels: enhancement, bugfix, debug tools

#297 Implement cast_ray_predicate to allow filtering the colliders with a function
  crates/bevy_xpbd_3d/examples/cast_ray_predicate.rs
  src/plugins/collision/mod.rs
  src/plugins/spatial_query/pipeline.rs
  src/plugins/spatial_query/system_param.rs
Labels: enhancement, spatial queries
